default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: traffic_backend_development
  user: postgres

test:
  <<: *default
  database: traffic_backend_test
  user: postgres

production:
  <<: *default
  database: traffic_backend_production
  username: traffic_backend
  password: <%= ENV["TRAFFIC_BACKEND_DATABASE_PASSWORD"] %>
