IpInfo.find_or_create_by(address: '::1', latitude: 0, longitude: 0, is_vpn: false)
IpInfo.find_or_create_by(address: '127.0.0.1', latitude: 0, longitude: 0, is_vpn: false)
Page.find_or_create_by(id: 1, name: 'index', url: 'http://localhost:1234/pages/')
Page.find_or_create_by(id: 2, name: 'about', url: 'http://localhost:1234/pages/about')
Page.find_or_create_by(id: 3, name: 'contact', url: 'http://localhost:1234/pages/contact')
